# Jordan P

## Research question/interests

Briefly describe your research question or interests here.

In [ ]:
import pandas as pd

list_movie = pd.read_csv("../data/raw/top_movies.csv")
list_movie

,production_year,id,title,directors,genres,camera_format,negative_format,budget,budget_source,film_type
0,2006,4103791,Pirates of the Caribbean: Dead Man's Chest,"Verbinski, Gore",Action|Adventure|Fantasy,"Arriflex 235, Panavision Primo Lenses|Panavisi...",35 mm,225000000,the-numbers,F
1,2006,4022547,Night at the Museum,"Levy, Shawn",Adventure|Comedy|Family|Fantasy,"Arriflex 435, Zeiss Ultra Prime and Angenieux ...",35 mm,110000000,the-numbers,F
2,2006,3415583,Cars,"Lasseter, John|Ranft, Joe",Animation|Comedy|Family|Sport,NaN,Digital,70000000,the-numbers,D
3,2006,4587958,X-Men: The Last Stand,"Ratner, Brett",Action|Adventure|Fantasy|Sci-Fi|Thriller,Panavision Cameras and Lenses,35 mm,210000000,the-numbers,F
4,2006,4351263,The Da Vinci Code,"Howard, Ron",Mystery|Thriller,"Arricam LT, Cooke S4 Lenses|Arricam ST, Cooke ...",35 mm,125000000,the-numbers,F
...,...,...,...,...,...,...,...,...,...,...
1190,2017,3954779,Megan Leavey,"Cowperthwaite, Gabriela",Biography|Drama|War,Arri Alexa,NaN,0,the-numbers,D
1191,2017,4375083,The Greatest Showman,"Gracey, Michael",Biography|Drama|Musical,Arri Alexa 65,Codex,84000000,the-numbers,D
1192,2016,4367698,The Founder,"Hancock, John Lee",Biography|Drama|History,"Arri Alexa XT, Panavision G- Series Lenses",Codex ARRIRAW,10500000,the-numbers,D
1193,2017,3342703,Battle of the Sexes,"Dayton, Jonathan|Faris, Valerie",Biography|Comedy|Drama|Sport,"Arricam LT, Kowa Cine Prominar prime and Angen...",35 mm,25000000,the-numbers,F
1194,2017,4332562,The Beguiled,"Coppola, Sofia",Drama|War,"Arricam LT, Zeiss Master Prime and Angenieux O...",35 mm,10500000,imdb,F